name: Build Android APK Otomatis (Tanpa Wrapper)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Ambil Kode dari Repositori
      uses: actions/checkout@v4

    - name: 2. Set up JDK 17 (Mesin Java)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 3. Set up Gradle Global
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '9.3.1' 

    # DI SINI KUNCINYA: Robot GitHub bakal otomatis bikin file debug.keystore sendiri
    - name: 4. Buat debug.keystore Otomatis
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: 5. Jalankan Proses Build APK
      run: gradle assembleDebug

    - name: 6. Upload File APK Jadi
      uses: actions/upload-artifact@v4
      with:
        name: motocare-assist-APK
        path: app/build/outputs/apk/debug/*.apk